Check:
  check_log:
    weight: 10
    hostname: compute-001
  process_check:
    weight: 160
    args:
      service: nova-compute
      hostname: compute-001
Action:
  restart_service:
    args:
      service: nova-compute
      hostname: compute-001
Tie:
  level: 'Node'
  Server:
    - 'base'
